# Generated by Django 4.0.4 on 2022-05-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbr_srv_side.server')),
            ],
            options={
                'verbose_name': 'ServerData',
                'managed': True,
            },
        ),
    ]
