# Generated by Django 4.0.4 on 2022-05-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0002_serverdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', unique=True, verbose_name='íp_address'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbr_srv_side.server', to_field='ip_address'),
        ),
    ]
